### ISSUE TITLE
Add button to show subway surfers gameplay

### ISSUE THREAD

**Issue by EliasJRH** [CarletonURocketry/hybrid-engine-ui#19]
The ground-station-ui should have a button that when pressed displays subway surfers gameplay. This is an absolutely critical component as there is no other way that the hybrid control operators will be able to hold their focus long enough unless there is something to keep their attention

**Comment by bskdany** [comment]
Bumping the issue, more awareness is needed

**Comment by linguini1** [comment]
Bump!

**Comment by justapotato213** [comment]
Number one priority of avionics, we need all of the team for this.

**Comment by auriza-jpg** [comment]
BUMP! How has this not been implemented yet???? This is at least a CVSS 9.9

**Comment by AritroSaha10** [comment]
bump
