### ISSUE TITLE
Allow for selection of network interface when joining multicast group

### ISSUE THREAD

**Issue by EliasJRH** [CarletonURocketry/hybrid-engine-ui#21]
Devices are setup such that whenever an application joins a multicast group, the network interface of that device adds the IP address of that multicast group to a list of addresses that the network interface is listening to. On windows, we can see the addresses that each network interface is listening to by running `netsh interface ip show joins`

![image](https://github.com/user-attachments/assets/4790c5f7-3f96-43f9-b7d8-db24f619a44d)

Most network interfaces that we interact with will be listening to `224.0.0.1`, `224.0.0.251`, `224.0.0.252` and, `239.255.255.250` by default. The first 3 are "technically" reserved for other purposed but seem to be rarely used, the last one is one that can be used for other purposes as per [this](https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml).

For devices with only a single network interface that we interact with this doesn't seem to be an issue, however most laptops seem to have multiple network interfaces that the hybrid engine UI won't add the multicast address to. The good news is that we can specify the network interface that we want to listen on using some QT functions.

Let's add another optional input box that specifies the IP address of the interface we want to open the port on. Let's also maybe change the UI to indicate which fields are necessary (mcast address & and port).

**Comment by VorteX254** [comment]
Just as a heads-up, did some research and maybe we shouldn't use `239.255.255.250` since it used for UPnP (Universal Plug and Play)/SSDP (Simple Service Discovery Protocol). So there is too much traffic and DDOS attacks in that IP.

**Comment by EliasJRH** [comment]
Nice find! We could definitely use this then so we can pick our own address.
